openapi: 3.0.0
info:
  title: InvigiClub API
  version: 1.0.0
  description: API for InvigiClub application

paths:
  /auth/login:
    $ref: "paths/auth/login.yaml"
  /auth/logout:
    $ref: "paths/auth/logout.yaml"
  /auth/refresh-token:
    $ref: "paths/auth/refresh-token.yaml"

  /organizations:
    get:
      $ref: "paths/organizations/list.yaml#/get"
    post:
      $ref: "paths/organizations/create.yaml#/post"
  /organizations/{publicId}:
    get:
      $ref: "paths/organizations/get.yaml#/get"
    patch:
      $ref: "paths/organizations/edit.yaml#/patch"

  /users:
    get:
      $ref: "paths/users/list.yaml#/get"
    post:
      $ref: "paths/users/create.yaml#/post"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      $ref: "schemas/user/user.yaml"
    UserCreateRequest:
      $ref: "schemas/user/create-request.yaml"
    Organization:
      $ref: "schemas/organization/organization.yaml"
    OrganizationCreateRequest:
      $ref: "schemas/organization/create-request.yaml"
    OrganizationUpdateRequest:
      $ref: "schemas/organization/update-request.yaml"
    ErrorDefault:
      $ref: "schemas/common/error-default.yaml"
    Error400:
      $ref: "schemas/common/error-400.yaml"
