openapi: 3.0.0
info:
  title: InvigiClub API
  version: 1.0.0
  description: API for InvigiClub application

servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /auth/login:
    $ref: "paths/auth/login.yaml"
  /auth/logout:
    $ref: "paths/auth/logout.yaml"
  /auth/refresh-token:
    $ref: "paths/auth/refresh-token.yaml"
  /auth/forgot-password:
    $ref: "paths/auth/forgot-password.yaml"
  /auth/reset-password:
    $ref: "paths/auth/reset-password.yaml"

  /registration:
    post:
      $ref: "paths/registration/create.yaml#/post"
  
  /activation/resend-link:
    post:
      $ref: "paths/activation/resend-activation-link.yaml#/post"
  /activation/account-activate:
    patch:
      $ref: "paths/activation/account-activate.yaml#/patch"
      

  /organizations:
    get:
      $ref: "paths/organizations/organization/list.yaml#/get"
    post:
      $ref: "paths/organizations/organization/create.yaml#/post"
  /organizations/{publicId}:
    get:
      $ref: "paths/organizations/organization/get.yaml#/get"
    patch:
      $ref: "paths/organizations/organization/edit.yaml#/patch"
  /organizations/{publicId}/statistics:
    get:
      $ref: "paths/organizations/organization/get-statistic.yaml#/get"

  /organizations/{organizationId}/members:
    get:
      $ref: "paths/organizations/member/list.yaml#/get"
    post:
      $ref: "paths/organizations/member/create.yaml#/post"
  /organizations/{organizationId}/members/{memberId}:
    get:
      $ref: "paths/organizations/member/get.yaml#/get"
    put:
      $ref: "paths/organizations/member/edit.yaml#/put"

  /organizations/{organizationId}/teams:
    post:
      $ref: "paths/organizations/team/create.yaml#/post"
    get:
      $ref: "paths/organizations/team/list.yaml#/get"
    delete:
      $ref: "paths/organizations/team/delete.yaml#/delete"
  /organizations/{organizationId}/teams/{teamId}:
    get:
      $ref: "paths/organizations/team/get.yaml#/get"
    patch:
      $ref: "paths/organizations/team/edit.yaml#/patch"
      
  /organizations/{organizationId}/invitation/resend:
    post:
      $ref: "paths/organizations/invitation/resend-invitation.yaml#/post"
      
  /organizations/{organizationId}/invitation/cancel:
    post:
      $ref: "paths/organizations/invitation/cancel-invitation.yaml#/post"
    
    
  /users:
    get:
      $ref: "paths/users/list.yaml#/get"
    post:
      $ref: "paths/users/create.yaml#/post"

  /users/me:
    get:
      $ref: "paths/users/get-current.yaml#/get"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      $ref: "schemas/user/user.yaml"
    CurrentUser:
      $ref: "schemas/user/current-user.yaml"
    UserCreateRequest:
      $ref: "schemas/user/create-request.yaml"
    Organization:
      $ref: "schemas/organization/organization.yaml"
    OrganizationCreateRequest:
      $ref: "schemas/organization/create-request.yaml"
    OrganizationUpdateRequest:
      $ref: "schemas/organization/update-request.yaml"
    ErrorDefault:
      $ref: "schemas/common/error-default.yaml"
    Error400:
      $ref: "schemas/common/error-400.yaml"
    Error401:
      $ref: "schemas/common/error-401.yaml"
    Error409:
      $ref: "schemas/common/error-409.yaml"
