openapi: "3.0.0"
info:
  version: 1.0.0
  title: Boilerplate example API
servers:
  - url: http://localhost:3000/api

paths:
  /organizations:
    $ref: "paths/organizations.yaml"
  /organizations/{publicId}:
    $ref: "paths/organizations/{publicId}.yaml"
  /auth/login:
    $ref: "paths/auth/login.yaml"
  /auth/refresh-token:
    $ref: "paths/auth/refresh-token.yaml"
  /auth/logout:
    $ref: "paths/auth/logout.yaml"
  /users:
    $ref: "paths/users.yaml"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      $ref: "schemas/user/user.yaml"
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    CreateUserRequest:
      $ref: "schemas/user/create-request.yaml"
    Organization:
      $ref: "schemas/organization/organization.yaml"
    OrganizationRequest:
      $ref: "schemas/organization/create-request.yaml"
    OrganizationUpdateRequest:
      $ref: "schemas/organization/update-request.yaml"
    ErrorDefault:
      $ref: "schemas/common/error-default.yaml"
    Error400:
      $ref: "schemas/common/error-400.yaml"
