on:
  workflow_call:

jobs:
  CheckLint:
    name: "Run linter and prettier"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Install node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
      - name: "Install dependencies"
        run: npm ci --include=optional
      - name: "Lint check"
        run: npm run lint:check
      - name: "Prettier check"
        run: npm run format:check
  RunTests:
    name: "Run tests"
    runs-on: ubuntu-latest
    needs: CheckLint
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Install node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
      - name: "Install dependencies"
        run: npm ci --include=optional
      - name: "Run unit tests"
        run: npm run test
  Build:
    name: "Build"
    runs-on: ubuntu-latest
    needs: RunTests
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: "Install node"
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
      - name: "Install dependencies"
        run: npm ci --include=optional
      - name: "Build"
        run: npm run build
